### PR TITLE
Update for Cloud 5 packages

### PR DESCRIPTION
**Pull request by vuntz**

### CODE REVIEW

**Comment by aspiers** [comment]
+1 apart from that one comment.

**Comment by vuntz** [comment]
> Can you make it explicit how this list was generated?

It's using the script that is in git. I just renamed the file to `foo-sle12` after having run the script :-)

**Comment by aspiers** [comment]
Yeah but with which media directory?

**Comment by vuntz** [comment]
> Yeah but with which media directory?

With the ISO mounted somewhere. That's how I always updated these files :-)

**Comment by vuntz** [comment]
(or maybe I'm not understanding your question?)

**Comment by aspiers** [comment]
> With the ISO mounted somewhere.

*Which* ISO?  It may be obvious to some, but with the rapidly increasing number of ISOs and repos, I'd rather make it explicit.

**Comment by vuntz** [comment]
The SLE12-Cloud-Compute one. I'm just not sure which other ISO this could be? It's clearly obvious to me, indeed. I added that to the commit message.

**Comment by aspiers** [comment]
Thanks, +1.

We're also using the SLES12 iso.  To you and me it's clear that's not relevant, but not everyone is very familiar with this plugin.

**Pull request merged**
