### PR TITLE
Export chef nodes, roles and data bags

### PR DESCRIPTION
**Pull request by vuntz**

### CODE REVIEW

**Comment by jsuchome** [comment]
What about saving ``/var/log/crowbar/chef-export`` to variable? Would it help readability?

**Comment by bkutil** [comment]
I agree w/ Jiri, otherwise, it looks good.

**Comment by vuntz** [comment]
> What about saving ``/var/log/crowbar/chef-export`` to variable? Would it help readability?

Done

**Comment by jsuchome** [comment]
+1

**Pull request merged**
